development:
  adapter:  postgresql
  encoding: unicode
  database: fenrir_dev
  pool:     5
  username: fenrirdev
  password: rainbowsinmywine
  host:     localhost

test:
  adapter:  postgresql
  encoding: unicode
  database: fenrir_test
  pool:     5
  username: fenrirdev
  password: rainbowsinmywine
  host:     localhost

