# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 352bc6604027b4ad5cdcaa0a5af66e100499854d320b462beed2a0143693f8a988c3418123798716f6be6a0667c12ee6516a046c1d6c5747e979c0236ddb37e3

test:
  secret_key_base: 5a98c97b015fbf0ed0a0d5e11321ed4ffdedd210d8d596c66513b0c0d65bac7e5899faf29d83aaa4944485bbac8b4e42d665f6ae392ae3ff68dd18997c5cfe8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
